import {useEffect,useState} from 'react';
import {useAdminApplication} from '@sarmg/admin-shell';
import {Button,ErrorState,FormField,LoadingState,PageHeader,Select,Table,TextField} from '@sarmg/admin-ui';
import {request,type Category} from './api';

type Kind='latest'|'recommended'|'category';
export type HomeSection={id:number;title:string;kind:Kind;sort_id:number|null;priority:number;enabled:boolean};
const isSections=(value:unknown):value is HomeSection[]=>Array.isArray(value)&&value.every(item=>typeof item==='object'&&item!==null&&'title'in item&&typeof item.title==='string'&&'kind'in item&&typeof item.kind==='string');

export function HomeSectionsPage(){
  const {client,notify}=useAdminApplication();
  const [rows,setRows]=useState<HomeSection[]|null>(null);
  const [categories,setCategories]=useState<Category[]>([]);
  const [failure,setFailure]=useState('');
  const [saving,setSaving]=useState(false);
  useEffect(()=>{const controller=new AbortController();void client.request('/api/v2/content/home-sections',isSections,{signal:controller.signal}).then(setRows).catch(()=>setFailure('首页栏目加载失败'));void request<Category[]>('/api/v2/categories',{signal:controller.signal}).then(setCategories).catch(()=>setFailure('分类加载失败'));return()=>controller.abort();},[client]);
  function change(index:number,patch:Partial<HomeSection>){setRows(current=>current?.map((item,i)=>i===index?{...item,...patch}:item)||null);}
  function move(index:number,delta:number){setRows(current=>{if(!current||index+delta<0||index+delta>=current.length)return current;const next=[...current];[next[index],next[index+delta]]=[next[index+delta],next[index]];return next;});}
  async function save(){if(!rows)return;setFailure('');setSaving(true);try{const payload=rows.map((item,index)=>({title:item.title.trim(),kind:item.kind,sort_id:item.kind==='category'?item.sort_id:null,priority:index*10,enabled:item.enabled}));if(payload.some(item=>!item.title||(item.kind==='category'&&!item.sort_id)))throw new Error('请填写栏目标题并选择分类');const updated=await client.request('/api/v2/content/home-sections',isSections,{method:'PUT',body:JSON.stringify(payload)});setRows(updated);notify('首页栏目已保存');}catch(reason){setFailure(reason instanceof Error?reason.message:'保存失败');}finally{setSaving(false);}}
  return <section className="sarmg-content-stack"><PageHeader><div><p className="eyebrow">HOME</p><h1>首页栏目</h1><p>设置栏目、顺序和展示内容。推荐栏目使用文章的“推荐”状态。</p></div><Button className="primary-action" disabled={saving||!rows} onClick={()=>void save()}>{saving?'保存中…':'保存栏目'}</Button></PageHeader>{failure&&<ErrorState>{failure}</ErrorState>}{rows?<><div className="sarmg-actions"><Button disabled={rows.length>=12} onClick={()=>setRows(current=>[...(current||[]),{id:-Date.now(),title:'新栏目',kind:'category',sort_id:categories[0]?.id||null,priority:current?.length||0,enabled:true}])}>新增分类栏目</Button></div><Table aria-label="首页栏目列表"><thead><tr><th>顺序</th><th>标题</th><th>内容来源</th><th>分类</th><th>显示</th><th>操作</th></tr></thead><tbody>{rows.map((item,index)=><tr key={item.id}><td>{index+1}</td><td><FormField label={`栏目 ${index+1} 标题`}><TextField maxLength={32} value={item.title} onChange={event=>change(index,{title:event.target.value})}/></FormField></td><td><Select aria-label={`栏目 ${index+1} 内容来源`} value={item.kind} onChange={event=>{const kind=event.target.value as Kind;change(index,{kind,sort_id:kind==='category'?(categories[0]?.id||null):null});}}><option value="latest">最新文章</option><option value="recommended">推荐文章</option><option value="category">指定分类</option></Select></td><td>{item.kind==='category'?<Select aria-label={`栏目 ${index+1} 分类`} value={item.sort_id||0} onChange={event=>change(index,{sort_id:Number(event.target.value)})}><option value={0}>选择分类</option>{categories.map(category=><option key={category.id} value={category.id}>{category.sort_name}</option>)}</Select>:'—'}</td><td><label><input type="checkbox" checked={item.enabled} onChange={event=>change(index,{enabled:event.target.checked})}/> 启用</label></td><td><div className="sarmg-actions"><Button aria-label={`上移栏目 ${index+1}`} disabled={index===0} onClick={()=>move(index,-1)}>↑</Button><Button aria-label={`下移栏目 ${index+1}`} disabled={index===rows.length-1} onClick={()=>move(index,1)}>↓</Button><Button className="sarmg-danger" onClick={()=>setRows(current=>current?.filter((_,i)=>i!==index)||null)}>删除</Button></div></td></tr>)}</tbody></Table></>:<LoadingState />}</section>;
}
