import { isCategories, isHomeSections, type HomeSection } from './public-contracts';
import { DisplayError } from './api';
import { publicErrorMessage } from './api';
import { t } from '@xcss/web/admin-ui/i18n';
import {useEffect,useState} from 'react';
import {useAdminApplication} from '@xcss/web/admin-shell';
import {Button,ErrorState,FormField,LoadingState,PageHeader,Select,Table,TextField} from '@xcss/web/admin-ui';
import {request,type Category} from './api';

type Kind=HomeSection['kind'];
export type {HomeSection} from './public-contracts';

export function HomeSectionsPage(){
  const {client,notify}=useAdminApplication();
  const [rows,setRows]=useState<HomeSection[]|null>(null);
  const [categories,setCategories]=useState<Category[]>([]);
  const [failure,setFailure]=useState('');
  const [saving,setSaving]=useState(false);
  const [version,setVersion]=useState(0);
  useEffect(()=>{const controller=new AbortController();void client.request('/api/v1/content/home-sections',isHomeSections,{signal:controller.signal}).then(value=>{if(!controller.signal.aborted){setRows(value);setFailure('');}}).catch(()=>{if(!controller.signal.aborted)setFailure(t("首页栏目加载失败", "Unable to load home sections"));});void request('/api/v1/categories', isCategories,{signal:controller.signal}).then(value=>{if(!controller.signal.aborted)setCategories(value);}).catch(()=>{if(!controller.signal.aborted)setFailure(t("分类加载失败", "Unable to load categories"));});return()=>controller.abort();},[client,version]);
  function change(index:number,patch:Partial<HomeSection>){setRows(current=>current?.map((item,i)=>i===index?{...item,...patch}:item)||null);}
  function move(index:number,delta:number){setRows(current=>{if(!current||index+delta<0||index+delta>=current.length)return current;const next=[...current];[next[index],next[index+delta]]=[next[index+delta],next[index]];return next;});}
  async function save(){if(!rows)return;setFailure('');setSaving(true);try{const payload=rows.map((item,index)=>({title:item.title.trim(),kind:item.kind,sort_id:item.kind==='category'?item.sort_id:null,priority:index*10,enabled:item.enabled}));if(payload.some(item=>!item.title||(item.kind==='category'&&!item.sort_id)))throw new DisplayError(t("请填写栏目标题并选择分类", "Enter a section title and select a category"));const updated=await client.request('/api/v1/content/home-sections',isHomeSections,{method:'PUT',body:JSON.stringify(payload)});setRows(updated);notify(t("首页栏目已保存", "Home sections saved"));}catch(reason){setFailure(publicErrorMessage(reason, t("保存失败", "Unable to save")));}finally{setSaving(false);}}
  return <section className="xcss-content-stack"><PageHeader><div><h1>{t("首页栏目", "Home sections")}</h1><p>{t("设置栏目、顺序和展示内容。推荐栏目使用文章的“推荐”状态。", "Set sections, their order, and content. Recommended sections use articles marked as recommended.")}</p></div><Button disabled={saving||!rows} onClick={()=>void save()}>{saving?t("保存中…", "Saving…"):t("保存栏目", "Save sections")}</Button></PageHeader>{failure&&<ErrorState onRetry={()=>setVersion(value=>value+1)}>{failure}</ErrorState>}{rows?<><div className="xcss-actions"><Button disabled={rows.length>=12} onClick={()=>setRows(current=>[...(current||[]),{id:-Date.now(),title:t("新栏目", "New section"),kind:'category',sort_id:categories[0]?.id||null,priority:current?.length||0,enabled:true}])}>{t("新增分类栏目", "Add category section")}</Button></div><Table aria-label={t("首页栏目列表", "Home section list")}><thead><tr><th>{t("顺序", "Order")}</th><th>{t("标题", "Title")}</th><th>{t("内容来源", "Content source")}</th><th>{t("分类", "Category")}</th><th>{t("显示", "Show")}</th><th>{t("操作", "Actions")}</th></tr></thead><tbody>{rows.map((item,index)=><tr key={item.id}><td>{index+1}</td><td><FormField label={t("栏目 {0} 标题", "Section {0} title", [index+1])}><TextField maxLength={32} value={item.title} onChange={event=>change(index,{title:event.target.value})}/></FormField></td><td><Select aria-label={t("栏目 {0} 内容来源", "Section {0} content source", [index+1])} value={item.kind} onChange={event=>{const kind=event.target.value as Kind;change(index,{kind,sort_id:kind==='category'?(categories[0]?.id||null):null});}}><option value="latest">{t("最新文章", "Latest articles")}</option><option value="recommended">{t("推荐文章", "Recommended articles")}</option><option value="category">{t("指定分类", "Selected category")}</option></Select></td><td>{item.kind==='category'?<Select aria-label={t("栏目 {0} 分类", "Section {0} category", [index+1])} value={item.sort_id||0} onChange={event=>change(index,{sort_id:Number(event.target.value)})}><option value={0}>{t("选择分类", "Select a category")}</option>{categories.map(category=><option key={category.id} value={category.id}>{category.sort_name}</option>)}</Select>:'—'}</td><td><label><input type="checkbox" checked={item.enabled} onChange={event=>change(index,{enabled:event.target.checked})}/>{t(" 启用", " Enable")}</label></td><td><div className="xcss-actions"><Button aria-label={t("上移栏目 {0}", "Move section {0} up", [index+1])} disabled={index===0} onClick={()=>move(index,-1)}>↑</Button><Button aria-label={t("下移栏目 {0}", "Move section {0} down", [index+1])} disabled={index===rows.length-1} onClick={()=>move(index,1)}>↓</Button><Button className="xcss-danger" onClick={()=>setRows(current=>current?.filter((_,i)=>i!==index)||null)}>{t("删除", "Delete")}</Button></div></td></tr>)}</tbody></Table></>:!failure&&<LoadingState />}</section>;
}
